repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        files: ^backend/

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd frontend && npx eslint'
        language: system
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        exclude: ^(?!frontend/).*$

  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in .codespellrc
    rev: v2.4.1
    hooks:
    - id: codespell
